// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdgeapyqudevuvegukcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZ2VhcHlxdWRldnV2ZWd1a2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MTI0NzIsImV4cCI6MjA1OTM4ODQ3Mn0.SJSuBcNOIvy9E3JDngWMSmZDZoNw0w0S5XVJUNQd6lk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);